version: '3'
services:
  backend:
    build: .
    ports:
      - '5050:5050'
    depends_on:
      - mongo
    environment:
      - DB_URI=${DB_URI}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - PORT=${PORT}
      - CREDIT_CARDS_API=${CREDIT_CARDS_API}
    networks:
      - express-mongo

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  express-mongo:
    driver: bridge

volumes:
  mongo_data:
